// VVS Carpool v8 — shared UI kit. Import from "@/components/ui" (relative: "../components/ui").
export { cn } from "./cn";
export type { IconSlot } from "./icon";
export { renderIcon } from "./icon";

export { Button, IconButton, BUTTON_VARIANT } from "./Button";
export type { ButtonProps, ButtonVariant, ButtonSize, IconButtonProps, IconButtonVariant } from "./Button";
export { Card } from "./Card";
export type { CardProps, CardPadding, CardVariant } from "./Card";
export { Chip } from "./Chip";
export type { ChipProps } from "./Chip";
export { Pill, StatusBadge, LiveBadge, STOP_PILL_TONE, RIDER_PILL_TONE, RIDER_LABEL } from "./Badge";
export type { PillProps, PillTone, StatusBadgeProps } from "./Badge";
export { Input, Select, Textarea } from "./Field";
export type { InputProps, SelectProps, SelectOption, TextareaProps, FieldBaseProps } from "./Field";
export { Avatar, AvatarStack, initialsOf } from "./Avatar";
export type { AvatarProps, AvatarSize, AvatarTone } from "./Avatar";
export { ListRow } from "./ListRow";
export type { ListRowProps } from "./ListRow";
export { Skeleton } from "./Skeleton";
export type { SkeletonProps, SkeletonVariant } from "./Skeleton";
export { EmptyState } from "./EmptyState";
export type { EmptyStateProps } from "./EmptyState";
export { ToastHost, useToast } from "./Toast";
export type { ToastApi, ToastOptions, ToastTone } from "./Toast";
export { ConfirmDialog, ConfirmHost, useConfirm } from "./Confirm";
export type { ConfirmOptions, ConfirmDialogProps } from "./Confirm";
export { SegmentedControl } from "./SegmentedControl";
export type { SegmentedControlProps, SegmentOption } from "./SegmentedControl";
export { Stat } from "./Stat";
export type { StatProps, StatDelta } from "./Stat";
export { Sparkline } from "./Sparkline";
export type { SparklineProps } from "./Sparkline";
export { ProgressRail, formatEta, formatDelay } from "./ProgressRail";
export type { ProgressRailProps, RailItem } from "./ProgressRail";
export { TopBar } from "./TopBar";
export type { TopBarProps } from "./TopBar";
export { TabBar, APP_TABS, TABBAR_HEIGHT } from "./TabBar";
export type { TabBarProps, TabItem } from "./TabBar";
export { Spinner } from "./Spinner";
export type { SpinnerProps } from "./Spinner";
export { Divider } from "./Divider";
export type { DividerProps } from "./Divider";
export { SectionTitle } from "./SectionTitle";
export type { SectionTitleProps } from "./SectionTitle";
